volumes:
    static_files:
        name: sn_static_files
    media_files:
        name: sn_media_files

services:
    django:
        build:
            context: .
            dockerfile: Dockerfile
        image: sn:development
        container_name: sn_django
        command: /app/docker/start.sh server
        env_file:
            - .env
        ports:
            - 8000:8000
        volumes:       
            - .:/app
            - static_files:/app/static:rw
            - media_files:/app/media:rw
        network_mode: host
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8000/health/"]
            interval: 30s
            timeout: 10s
            retries: 3

    nginx:
        build:
            context: ./nginx
            dockerfile: Dockerfile
        image: sn_nginx:development
        container_name: sn_nginx
        ports:
            - 80:80
            - 443:443
        volumes:
            - static_files:/app/static:ro
            - media_files:/app/media:ro
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/nginx.dev.conf:/etc/nginx/conf.d/default.conf:ro
        depends_on:
            - django
        network_mode: host

    postgres:
        image: postgres:13.3-alpine
        hostname: sn-postgres
        container_name: sn_postgres
        ports:
            - "5433:5432"
        volumes:
            - app_data:/var/lib/postgresql/data
        env_file:
            - .env
        healthcheck:
            test: ["CMD-SHELL", "pg_isready -U postgres"]
            interval: 5s
            timeout: 5s
            retries: 5
    
    
    
