version: '3.8'

volumes:
    static_files:
        name: sn_static_files
    media_files:
        name: sn_media_files
    postgres_data:
        name: sn_postgres_data

services:
    db:
        image: postgres:13
        container_name: sn_postgres
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        ports:
            - "5432:5432"
        networks:
            - sn_network
        restart: always

    backend:
        build: ./backend
        container_name: sn_django
        command: >
            sh -c "python manage.py migrate &&
                   python manage.py runserver 0.0.0.0:8000"
        volumes:
            - ./backend:/app
        env_file:
            - .env
        depends_on:
            - db
        networks:
            - sn_network
        restart: always
        environment:
            - DATABASE_URL=postgres://postgres:postgres@db:5432/postgres
            - DEBUG=1
            - SECRET_KEY=django-insecure-your-secret-key-here

    frontend:
        build: ./frontend
        container_name: sn_frontend
        volumes:
            - ./frontend:/app
            - /app/node_modules
        ports:
            - "3000:3000"
        environment:
            - REACT_APP_API_URL=http://localhost:8000
        depends_on:
            - backend
        networks:
            - sn_network
        restart: always

    nginx:
        image: nginx:1.21-alpine
        container_name: sn_nginx
        volumes:
            - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
            - ./nginx/conf.d:/etc/nginx/conf.d:ro
        ports:
            - "80:80"
        depends_on:
            - backend
            - frontend
        networks:
            - sn_network
        restart: always

networks:
    sn_network:
        driver: bridge
    
    
    
