version: '3.8'

volumes:
    static_files:
        name: sn_static_files
    media_files:
        name: sn_media_files
    app_data:
        name: sn_app_data

services:
    postgres:
        image: postgres:15
        container_name: sn_postgres
        environment:
            POSTGRES_DB: snpostgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - app_data:/var/lib/postgresql/data
        networks:
            - sn_network
        restart: always

    django:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sn_django
        command: python manage.py runserver 0.0.0.0:8000
        volumes:
            - static_files:/app/static
            - media_files:/app/media
        environment:
            - DEBUG=1
            - SECRET_KEY=django-insecure-123
            - DJANGO_ALLOWED_HOSTS=localhost 127.0.0.1 [::1]
            - SQL_ENGINE=django.db.backends.postgresql
            - SQL_DATABASE=snpostgres
            - SQL_USER=postgres
            - SQL_PASSWORD=postgres
            - SQL_HOST=postgres
            - SQL_PORT=5432
        depends_on:
            - postgres
        networks:
            - sn_network
        restart: always

    nginx:
        build:
            context: .
            dockerfile: docker/nginx/Dockerfile
        container_name: sn_nginx
        volumes:
            - static_files:/app/static
            - media_files:/app/media
        ports:
            - "80:80"
        depends_on:
            - django
        networks:
            - sn_network
        restart: always

networks:
    sn_network:
        driver: bridge
    
    
    
