volumes:
    static_files:
        name: sn_static_files
    media_files:
        name: sn_media_files
    postgres_data:
        name: sn_postgres_data

services:
    postgres:
        image: postgres:15
        container_name: sn_postgres
        environment:
            POSTGRES_DB: snpostgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: postgres
        volumes:
            - postgres_data:/var/lib/postgresql/data
        networks:
            - sn_network
        restart: always

    django:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: sn_django
        command: >
          sh -c "python manage.py collectstatic --noinput &&
                 python manage.py migrate &&
                 (python manage.py shell -c 'from django.contrib.auth import get_user_model; User = get_user_model(); User.objects.filter(username=\"admin\").exists() or User.objects.create_superuser(\"admin\", \"admin@example.com\", \"admin123\")') &&
                 python manage.py runserver 0.0.0.0:8000"
        volumes:
            - static_files:/app/static:rw
            - media_files:/app/media:rw
        environment:
            - DJANGO_SUPERUSER_USERNAME=admin
            - DJANGO_SUPERUSER_EMAIL=admin@example.com
            - DJANGO_SUPERUSER_PASSWORD=admin123
        env_file:
            - .env
        depends_on:
            - postgres
        networks:
            - sn_network
        restart: always

    nginx:
        build:
            context: ./docker/nginx
            dockerfile: Dockerfile
        container_name: sn_nginx
        volumes:
            - static_files:/app/static:ro
            - media_files:/app/media:ro
        ports:
            - "80:80"
        depends_on:
            - django
        networks:
            - sn_network
        restart: always

    frontend:
        build: ./frontend
        ports:
            - "3000:80"
        environment:
            - VITE_API_URL=http://localhost:8000
        depends_on:
            - django
        networks:
            - sn_network
        restart: always

networks:
    sn_network:
        driver: bridge
    
    
    
