# Generated by Django 4.2.3 on 2025-04-06 09:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_alter_user_options_alter_notification_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='group',
            options={'verbose_name': 'Группу', 'verbose_name_plural': 'Группы'},
        ),
        migrations.AlterModelOptions(
            name='note',
            options={'verbose_name': 'Заметку', 'verbose_name_plural': 'Заметки'},
        ),
        migrations.AlterModelOptions(
            name='team',
            options={'verbose_name': 'Команду', 'verbose_name_plural': 'Команды'},
        ),
    ]
